# Sử dụng image Nginx chính thức từ Docker Hub
FROM 6011915/nomachine-ubuntu-desktop:xfce4

COPY ngrok /ngrok

COPY xfce4.sh /xfce4.sh

ENV USER=user
ENV PASSWORD=123456

USER root

RUN groupadd -r ${USER} -g 433 && useradd -u 431 -r -g ${USER} -d /home/${USER} -s /bin/bash -c "${USER}" ${USER} && adduser ${USER} sudo && mkdir /home/${USER} && \
chown -R ${USER}:${USER} /home/${USER} && echo ${USER}':'${PASSWORD} | chpasswd

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
ENV NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf '%s/.nvm' "${HOME}" || printf '%s/nvm' "${XDG_CONFIG_HOME}")"
RUN [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
RUN [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
RUN nvm install 14
RUN nvm use 14

RUN apt-get update && apt-get install -y \
    git \
    apt install openjdk-11-jdk \
    apt-get clean

ENV JAVA_HOME=/usr/lib/java-11-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"

#RUN chown -R nx:nx /etc/NX

#RUN chown -R nx:nx /usr/NX/scripts

#RUN chown -R nx:nx /usr/NX/bin

#RUN chown -R nx:nx /usr/NX/etc

#RUN chmod -R 777 /usr/NX/scripts

#RUN	mkdir -p /usr/NX/bin 

#RUN chmod -R 777 /usr/NX/bin

#RUN chmod -R 777 /usr/NX

#RUN chmod  0400 /usr/NX/etc/server.lic

#RUN	mkdir -p /etc/NX

#RUN chmod -R 777 /etc/NX

RUN chmod -R 777 /xfce4.sh

RUN chmod -R 777 /ngrok

# Expose port 80 để nhận request
#EXPOSE 4040

# Khởi động Nginx
#ENTRYPOINT ["/bin/bash", "-c", "/etc/NX/nxserver --startup && tail -f /dev/null"]
